### ISSUE TITLE
clip - echo username

### ISSUE THREAD

**Issue by dncohen** [johnathanhowell/masterkey#6]
What do you think of `clip` echoing the username, and maybe other metadata, but not password?  So more like `get` except passwords never shown.  Seems like there should be some way to recall your username if you've forgotten it without also showing password.
  
Almost as good would be a `clear` command to remove from screen anything recently shown.  
(unrelated, I wonder if https://github.com/abiosoft/ishell would save you some work supporting commands)

**Comment by johnathanhowell** [comment]
As of 11ffe3b38901fa184d295db5dce09c478a60de4d the `clip` command now echoes back the `username` or `meta name` that was used to copy the credential, for example:

```
masterkey [vault.db] > clip github.com
johnathanhowell@github.com copied to clipboard, will clear in 30 seconds
masterkey [vault.db] > clip github.com 2fa
2fa@github.com copied to clipboard, will clear in 30 seconds
```

I agree that a `clear` command, as well as command history, would be a nice addition to the `repl` package.

**Comment by dncohen** [comment]
nice!
